name: FISCO-BCOS GitHub Actions
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [published, created, edited]
jobs:
  build_with_vcpkg:
    name: build_with_vcpkg
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04,windows-2019,macos-latest]
        package_manager: [hunter,vcpkg]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - name: Prepare windows msbuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
      - name: Prepare linux gcc-10
        if: runner.os == 'Linux'
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
      - name: Prepare macos llvm clang
        if: runner.os == 'macOS'
        run: |
          rm /usr/bin/clang
          rm /usr/bin/clang++
          ln -s $(brew --prefix llvm)/bin/clang /usr/bin/clang
          ln -s $(brew --prefix llvm)/bin/clang++ /usr/bin/clang++
      - name: Prepare hunter
        if: matrix.package_manager == 'hunter'
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            /home/runner/.hunter
            /Users/runner/.hunter/
            deps/src
          key: hunter-clang-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            hunter-clang-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            hunter-clang-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-
            hunter-clang-v8-notest-${{ runner.temp }}-
      - name: Prepare vcpkg
        if: matrix.package_manager == 'vcpkg'
        uses: friendlyanon/setup-vcpkg@v1
        with: { committish: 7e3dcf74e37034eea358934a90a11d618520e139 }
      - name: Configure with vcpkg
        if: matrix.package_manager == 'vcpkg'
        run:
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DHUNTER_ENABLED=OFF -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake ../
      - name: Configure with hunter
        if: matrix.package_manager == 'hunter'
        run:
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DHUNTER_ENABLED=ON ../
      - name: Compile
        run: 
          cd build && cmake --build . --parallel
      - name: Test
        if: runner.os != 'Windows'
        run:
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE ctest